export const HEADERS_LIST = {
	Accept: "*/*",
	"Accept-Encoding": "gzip, deflate, br, zstd",
	"Accept-Language": "en-US,en;q=0.9",
	"Api-Key": process.env.API_KEY,
	"Classification-Id": "1",
	Connection: "keep-alive",
	"Content-Type": "application/json",
	Host: "datawomb.com",
	Origin: "https://valvesonly.com",
	Referer: "https://valvesonly.com/",
	"Sec-Fetch-Dest": "empty",
	"Sec-Fetch-Mode": "cors",
	"Sec-Fetch-Site": "cross-site",
	"User-Agent":
		"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0",
	"sec-ch-ua": `"Not/A)Brand";v="8", "Chromium";v="126","Microsoft Edge";v="126""`,
	"sec-ch-ua-mobile": "?0",
	"sec-ch-ua-platform": `"Windows"`,
};
